"""change request, role binding e execution

Revision ID: 0255c732fbe4
Revises: 7a1c0f2d9b43
Create Date: 2026-09-14 13:20:33.944347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0255c732fbe4'
down_revision: Union[str, Sequence[str], None] = '7a1c0f2d9b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_binding',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('scope_domain', sa.String(length=64), nullable=True),
    sa.Column('scope_environment', sa.String(length=16), nullable=True),
    sa.Column('scope_host', sa.String(length=255), nullable=True),
    sa.Column('granted_by', sa.String(length=255), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.CheckConstraint("role in ('batch.viewer','batch.operator','batch.operator-prod','batch.admin')", name=op.f('ck_role_binding_role_valida')),
    sa.CheckConstraint("scope_environment is null or scope_environment in ('PROD','UAT','TEST','DEV')", name=op.f('ck_role_binding_scope_environment_valido')),
    sa.CheckConstraint("subject_type in ('user','group')", name=op.f('ck_role_binding_subject_type_valido')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_binding')),
    schema='catalog'
    )
    op.create_index('ix_role_binding_role', 'role_binding', ['role'], unique=False, schema='catalog')
    op.create_index('ix_role_binding_subject', 'role_binding', ['subject'], unique=False, schema='catalog')
    op.create_table('crontab_change_request',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('desired_status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('marker', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_by', sa.String(length=255), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.CheckConstraint("desired_status in ('active','disabled')", name=op.f('ck_crontab_change_request_desired_status_valido')),
    sa.CheckConstraint("state in ('pending','applied','verified','cancelled','expired')", name=op.f('ck_crontab_change_request_state_valido')),
    sa.ForeignKeyConstraint(['job_id'], ['catalog.job.id'], name=op.f('fk_crontab_change_request_job_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_snapshot_id'], ['catalog.crontab_snapshot.id'], name=op.f('fk_crontab_change_request_verified_snapshot_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crontab_change_request')),
    schema='catalog'
    )
    op.create_index('ix_crontab_change_request_job_id', 'crontab_change_request', ['job_id'], unique=False, schema='catalog')
    op.create_index('ix_crontab_change_request_state', 'crontab_change_request', ['state'], unique=False, schema='catalog')
    op.create_table('execution',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('requested_steps', sa.ARRAY(sa.String(length=16)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('dates_pattern', sa.ARRAY(sa.String(length=32)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('no_mail', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('backend', sa.String(length=32), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('worker', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('log_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.CheckConstraint("result is null or result in ('success','failure','partial')", name=op.f('ck_execution_result_valido')),
    sa.CheckConstraint("status in ('queued','running','succeeded','failed','cancelled')", name=op.f('ck_execution_status_valido')),
    sa.CheckConstraint("trigger in ('schedule','manual','reprocess','event','dependency')", name=op.f('ck_execution_trigger_valido')),
    sa.ForeignKeyConstraint(['job_id'], ['catalog.job.id'], name=op.f('fk_execution_job_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution')),
    sa.UniqueConstraint('idempotency_key', name='uq_execution_idempotency_key'),
    schema='catalog'
    )
    op.create_index('ix_execution_job_id_started_at', 'execution', ['job_id', 'started_at'], unique=False, schema='catalog')
    op.create_index('ix_execution_status', 'execution', ['status'], unique=False, schema='catalog')
    # A FK ciclica `job.current_contract_version_id` pertence a migration base
    # (32bcec64786a), que a cria com ALTER explicito. O autogenerate a reofereceu
    # aqui porque o banco de DEV foi migrado antes daquela correcao — e recria-la
    # quebraria um banco novo, onde ela ja existe.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_execution_status', table_name='execution', schema='catalog')
    op.drop_index('ix_execution_job_id_started_at', table_name='execution', schema='catalog')
    op.drop_table('execution', schema='catalog')
    op.drop_index('ix_crontab_change_request_state', table_name='crontab_change_request', schema='catalog')
    op.drop_index('ix_crontab_change_request_job_id', table_name='crontab_change_request', schema='catalog')
    op.drop_table('crontab_change_request', schema='catalog')
    op.drop_index('ix_role_binding_subject', table_name='role_binding', schema='catalog')
    op.drop_index('ix_role_binding_role', table_name='role_binding', schema='catalog')
    op.drop_table('role_binding', schema='catalog')
    # ### end Alembic commands ###
