"""catalogo, auditoria e reconciliacao

Revision ID: 32bcec64786a
Revises: 
Create Date: 2026-09-10 17:40:31.072727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32bcec64786a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # A migration não pode depender de schema pré-criado à mão: em banco novo
    # (RDS recém-provisionado, banco de teste) ela tem de bastar por si.
    op.execute("CREATE SCHEMA IF NOT EXISTS catalog")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")   # gen_random_uuid()
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gin")  # indice de country_codes

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.CheckConstraint("source in ('ui','api','cli','job','ssh')", name=op.f('ck_audit_event_source_valida')),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name=op.f('pk_audit_event')),
    schema='catalog',
    postgresql_partition_by='RANGE (occurred_at)'
    )
    op.create_index('ix_audit_event_actor_occurred_at', 'audit_event', ['actor', 'occurred_at'], unique=False, schema='catalog')
    op.create_index('ix_audit_event_target', 'audit_event', ['target_type', 'target_id'], unique=False, schema='catalog')
    op.create_table('connection_alias',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('auth_method', sa.String(length=16), nullable=True),
    sa.Column('key_path', sa.Text(), nullable=True),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=True),
    sa.Column('vault_reference', sa.Text(), nullable=True),
    sa.Column('owners', sa.ARRAY(sa.String(length=255)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('validity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.CheckConstraint("auth_method is null or auth_method in ('key','password','iam','none')", name=op.f('ck_connection_alias_auth_method_valido')),
    sa.CheckConstraint("status in ('ok','broken','redundant','retired')", name=op.f('ck_connection_alias_status_valido')),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_connection_alias')),
    schema='catalog'
    )
    op.create_table('crontab_snapshot',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_by', sa.String(length=255), nullable=True),
    sa.Column('collector_version', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('framework_root', sa.Text(), nullable=True),
    sa.Column('total_lines', sa.Integer(), nullable=True),
    sa.Column('bundle_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crontab_snapshot')),
    sa.UniqueConstraint('host', 'captured_at', name='uq_crontab_snapshot_host_captured_at'),
    schema='catalog'
    )
    op.create_table('job',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('process_name', sa.String(length=255), nullable=False),
    sa.Column('wrapper_path', sa.Text(), nullable=True),
    sa.Column('contract_path', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.Column('environment', sa.String(length=16), nullable=True),
    sa.Column('client_code', sa.String(length=64), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('country_codes', sa.ARRAY(sa.String(length=8)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('criticality', sa.String(length=32), nullable=True),
    sa.Column('sla', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('current_contract_version_id', sa.UUID(), nullable=True),
    sa.Column('flags', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.CheckConstraint("environment is null or environment in ('PROD','UAT','TEST','DEV')", name=op.f('ck_job_environment_valido')),
    sa.CheckConstraint("kind in ('contract_job','script_task')", name=op.f('ck_job_kind_valido')),
    sa.CheckConstraint("status in ('active','disabled','on_demand','orphan','broken')", name=op.f('ck_job_status_valido')),
    sa.ForeignKeyConstraint(['current_contract_version_id'], ['catalog.job_contract_version.id'], name=op.f('fk_job_current_contract_version_id'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job')),
    schema='catalog'
    )
    op.create_index('ix_job_client_code', 'job', ['client_code'], unique=False, schema='catalog')
    op.create_index('ix_job_country_codes', 'job', ['country_codes'], unique=False, schema='catalog', postgresql_using='gin')
    op.create_index('ix_job_domain_environment_status', 'job', ['domain', 'environment', 'status'], unique=False, schema='catalog')
    op.create_index('uq_job_host_wrapper_contract', 'job', ['host', 'wrapper_path', sa.literal_column("coalesce(contract_path, '')")], unique=True, schema='catalog')
    op.create_table('crontab_entry',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('lineno', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_expr', sa.String(length=128), nullable=True),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('script_path', sa.Text(), nullable=True),
    sa.Column('log_path', sa.Text(), nullable=True),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('flags', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['catalog.crontab_snapshot.id'], name=op.f('fk_crontab_entry_snapshot_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crontab_entry')),
    sa.UniqueConstraint('snapshot_id', 'source', 'lineno', name='uq_crontab_entry_origem'),
    schema='catalog'
    )
    op.create_table('job_connection_alias',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('alias_name', sa.String(length=255), nullable=False),
    sa.Column('declared', sa.Boolean(), nullable=False),
    sa.Column('usages', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['catalog.job.id'], name=op.f('fk_job_connection_alias_job_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'alias_name', name=op.f('pk_job_connection_alias')),
    schema='catalog'
    )
    op.create_index('ix_job_connection_alias_alias_name', 'job_connection_alias', ['alias_name'], unique=False, schema='catalog')
    op.create_table('job_contract_version',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=True),
    sa.Column('contract', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contract_hash', sa.String(length=64), nullable=False),
    sa.Column('contract_bytes', sa.Integer(), nullable=True),
    sa.Column('steps_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.CheckConstraint("source in ('seed','import','api','reconciliation')", name=op.f('ck_job_contract_version_source_valida')),
    sa.ForeignKeyConstraint(['job_id'], ['catalog.job.id'], name=op.f('fk_job_contract_version_job_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_contract_version')),
    sa.UniqueConstraint('job_id', 'contract_hash', name='uq_job_contract_version_job_id_hash'),
    sa.UniqueConstraint('job_id', 'version', name='uq_job_contract_version_job_id_version'),
    schema='catalog'
    )
    op.create_table('job_revision',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audit_event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['catalog.job.id'], name=op.f('fk_job_revision_job_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_revision')),
    sa.UniqueConstraint('job_id', 'version', name='uq_job_revision_job_id_version'),
    schema='catalog'
    )
    op.create_table('job_schedule',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('schedule_expr', sa.String(length=128), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('catchup_policy', sa.String(length=32), nullable=True),
    sa.Column('manual_steps', sa.String(length=128), nullable=True),
    sa.Column('dates_pattern', sa.String(length=255), nullable=True),
    sa.Column('no_mail', sa.Boolean(), nullable=False),
    sa.Column('cron_source', sa.String(length=255), nullable=True),
    sa.Column('cron_lineno', sa.Integer(), nullable=True),
    sa.Column('log_path', sa.Text(), nullable=True),
    sa.Column('raw_line', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.CheckConstraint("catchup_policy is null or catchup_policy in ('skip','run_once','run_all')", name=op.f('ck_job_schedule_catchup_policy_valida')),
    sa.ForeignKeyConstraint(['job_id'], ['catalog.job.id'], name=op.f('fk_job_schedule_job_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_schedule')),
    sa.UniqueConstraint('job_id', 'cron_source', 'cron_lineno', name='uq_job_schedule_origem'),
    schema='catalog'
    )
    op.create_index('ix_job_schedule_enabled', 'job_schedule', ['enabled'], unique=False, schema='catalog')
    op.create_table('reconciliation_run',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('triggered_by', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['catalog.crontab_snapshot.id'], name=op.f('fk_reconciliation_run_snapshot_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_run')),
    schema='catalog'
    )
    op.create_table('reconciliation_finding',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('explained_by', sa.String(length=255), nullable=True),
    sa.Column('explained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.CheckConstraint("severity in ('erro','aviso','info')", name=op.f('ck_reconciliation_finding_severity_valida')),
    sa.CheckConstraint("status in ('open','explained','resolved')", name=op.f('ck_reconciliation_finding_status_valido')),
    sa.ForeignKeyConstraint(['job_id'], ['catalog.job.id'], name=op.f('fk_reconciliation_finding_job_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['catalog.reconciliation_run.id'], name=op.f('fk_reconciliation_finding_run_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_finding')),
    schema='catalog'
    )
    op.create_index('ix_reconciliation_finding_fingerprint', 'reconciliation_finding', ['fingerprint'], unique=False, schema='catalog')
    op.create_index('ix_reconciliation_finding_kind_status', 'reconciliation_finding', ['kind', 'status'], unique=False, schema='catalog')
    # ### end Alembic commands ###
    # `job.current_contract_version_id` e `job_contract_version.job_id`
    # formam ciclo; por isso a FK é marcada `use_alter` no modelo e o dialeto a
    # PULA no CREATE TABLE. Sem este ALTER explícito ela simplesmente não
    # existiria no banco (o teste de drift acusa).
    op.create_foreign_key(
        "fk_job_current_contract_version_id",
        "job",
        "job_contract_version",
        ["current_contract_version_id"],
        ["id"],
        source_schema="catalog",
        referent_schema="catalog",
    )

    # =======================================================================
    # DDL que o modelo não expressa. Três coisas, todas exigidas pelos
    # invariantes do projeto:
    #
    # 1. `audit_event` particionada por mês + partição DEFAULT. A partição
    #    default existe para que NENHUM evento seja perdido por falta de
    #    partição — perder trilha é pior que ter partição desbalanceada.
    #    A política de RETENÇÃO (quando descartar partição antiga) segue
    #    pendente no ADR-003 e não é decidida aqui.
    #
    # 2. Trigger que recusa UPDATE/DELETE nas tabelas append-only. Vale até
    #    para quem conecta como dono do schema ou superusuário.
    #
    # 3. REVOKE de UPDATE/DELETE da role da aplicação. É o controle primário;
    #    o trigger é a rede de proteção.
    # =======================================================================

    op.execute(
        """
        CREATE OR REPLACE FUNCTION catalog.ensure_audit_partition(p_month date)
        RETURNS text LANGUAGE plpgsql AS $fn$
        DECLARE
            v_start date := date_trunc('month', p_month)::date;
            v_end   date := (date_trunc('month', p_month) + interval '1 month')::date;
            v_name  text := format('audit_event_%s', to_char(v_start, 'YYYYMM'));
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_class c
                JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE n.nspname = 'catalog' AND c.relname = v_name
            ) THEN
                EXECUTE format(
                    'CREATE TABLE catalog.%I PARTITION OF catalog.audit_event '
                    'FOR VALUES FROM (%L) TO (%L)', v_name, v_start, v_end);
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'batch_app') THEN
                    EXECUTE format('GRANT SELECT, INSERT ON catalog.%I TO batch_app', v_name);
                END IF;
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'batch_readonly') THEN
                    EXECUTE format('GRANT SELECT ON catalog.%I TO batch_readonly', v_name);
                END IF;
            END IF;
            RETURN v_name;
        END $fn$;
        """
    )

    op.execute(
        "CREATE TABLE catalog.audit_event_default "
        "PARTITION OF catalog.audit_event DEFAULT"
    )

    # mês anterior, corrente e os dois seguintes
    op.execute(
        """
        DO $do$
        DECLARE m date;
        BEGIN
            FOR m IN
                SELECT generate_series(
                    date_trunc('month', now()) - interval '1 month',
                    date_trunc('month', now()) + interval '2 month',
                    interval '1 month')::date
            LOOP
                PERFORM catalog.ensure_audit_partition(m);
            END LOOP;
        END $do$;
        """
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION catalog.deny_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $fn$
        BEGIN
            RAISE EXCEPTION
                'tabela append-only: % em catalog.% nao e permitido',
                TG_OP, TG_TABLE_NAME
                USING ERRCODE = 'restrict_violation',
                      HINT = 'registre um novo evento/versao em vez de alterar o historico';
        END $fn$;
        """
    )

    for table in ("audit_event", "job_contract_version", "job_revision"):
        # FOR EACH ROW para que o trigger seja clonado nas partições
        op.execute(
            f"""
            CREATE TRIGGER {table}_append_only
            BEFORE UPDATE OR DELETE ON catalog.{table}
            FOR EACH ROW EXECUTE FUNCTION catalog.deny_mutation();
            """
        )
        op.execute(
            f"""
            DO $do$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'batch_app') THEN
                    EXECUTE 'REVOKE UPDATE, DELETE ON catalog.{table} FROM batch_app';
                END IF;
            END $do$;
            """
        )

    # Garante os privilégios das tabelas já criadas (ALTER DEFAULT PRIVILEGES
    # do init só vale para o que for criado depois dele).
    op.execute(
        """
        DO $do$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'batch_app') THEN
                EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA catalog TO batch_app';
                EXECUTE 'GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA catalog TO batch_app';
                EXECUTE 'REVOKE UPDATE, DELETE ON catalog.audit_event FROM batch_app';
                EXECUTE 'REVOKE UPDATE, DELETE ON catalog.job_contract_version FROM batch_app';
                EXECUTE 'REVOKE UPDATE, DELETE ON catalog.job_revision FROM batch_app';
            END IF;
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'batch_readonly') THEN
                EXECUTE 'GRANT SELECT ON ALL TABLES IN SCHEMA catalog TO batch_readonly';
            END IF;
        END $do$;
        """
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE catalog.job DROP CONSTRAINT IF EXISTS fk_job_current_contract_version_id"
    )
    for table in ("audit_event", "job_contract_version", "job_revision"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON catalog.{table}")
    op.execute("DROP FUNCTION IF EXISTS catalog.deny_mutation()")
    op.execute("DROP FUNCTION IF EXISTS catalog.ensure_audit_partition(date)")
    op.execute("DROP TABLE IF EXISTS catalog.audit_event_default")

    op.drop_index('ix_reconciliation_finding_kind_status', table_name='reconciliation_finding', schema='catalog')
    op.drop_index('ix_reconciliation_finding_fingerprint', table_name='reconciliation_finding', schema='catalog')
    op.drop_table('reconciliation_finding', schema='catalog')
    op.drop_table('reconciliation_run', schema='catalog')
    op.drop_index('ix_job_schedule_enabled', table_name='job_schedule', schema='catalog')
    op.drop_table('job_schedule', schema='catalog')
    op.drop_table('job_revision', schema='catalog')
    op.drop_table('job_contract_version', schema='catalog')
    op.drop_index('ix_job_connection_alias_alias_name', table_name='job_connection_alias', schema='catalog')
    op.drop_table('job_connection_alias', schema='catalog')
    op.drop_table('crontab_entry', schema='catalog')
    op.drop_index('uq_job_host_wrapper_contract', table_name='job', schema='catalog')
    op.drop_index('ix_job_domain_environment_status', table_name='job', schema='catalog')
    op.drop_index('ix_job_country_codes', table_name='job', schema='catalog', postgresql_using='gin')
    op.drop_index('ix_job_client_code', table_name='job', schema='catalog')
    op.drop_table('job', schema='catalog')
    op.drop_table('crontab_snapshot', schema='catalog')
    op.drop_table('connection_alias', schema='catalog')
    op.drop_index('ix_audit_event_target', table_name='audit_event', schema='catalog')
    op.drop_index('ix_audit_event_actor_occurred_at', table_name='audit_event', schema='catalog')
    op.drop_table('audit_event', schema='catalog')
    # ### end Alembic commands ###
